

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    ports:
      - "3000:3000"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
  flask_ml:
    build:
      context: .
      dockerfile: flask_ml/Dockerfile
    container_name: flask_ml
    ports:
      - "5000:5000"